f4t/src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

f4t/src/explore/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
   	url(r'^$', views.run, name='run'),
]

f4t/src/f4t/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^explore/', include('explore.urls')),
    url(r'^explore/', include('explore.urls', namespace="explore")),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

f4t/src/explore/models.py
from django.db import models

# Create your models here.

class Feature(models.Model):
    feature_text = models.CharField(max_length=100)
    

f4t/src/explore/views.py
# from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.template import loader

from htmlPlot import clusterPlot

def index(request):
	template=loader.get_template('explore/index.html')
	return HttpResponse(template.render(request))

# remember clusterPlot(data_csv,l,kl,ku):
def run(request):
	# Get parameters from form..
	l=request.POST['feature']
	kl=request.POST['kmin']
	ku=request.POST['kmax']
	data_csv='../data/CA_WHS_HOUSEHOLD.csv'
	# Perform clustering
	context=clusterPlot(data_csv,l,kl,ku)
	return HttpResponseRedirect(reverse('explore:results',args=context))

# I think we need to deal with the rendering of the run function via a 
#different rendering function

def results(request, context):
	# Redirects back to main view..
    return render(request, 'explore/index.html', {'viz': context})

f4t/src/templates/explore/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Explore{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          This is where the visualisation will go
          Ok, so we need a form here to get parameters for the visulisation
          <form action="{% url 'explore:run' %}" method="post">
          {% csrf_token %}
          {% for feature in explore.feature_set.all %}
              <input type="radio" name="feature" id="feature{{ forloop.counter }}" value="{{ feature.id }}" />
              <label for="feature{{ forloop.counter }}">{{ feature.feature_text }}</label><br />
          {% endfor %}
          <input type="submit" value="Cluster!" />
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %} - EXplore</h1>
          <p>Cluster and Visualise Variation in Diet across Refugee Populations</p>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>1. Select Cluster Variables</h2>
      <p>
        In order to enable interpretation of dietary habits, it is useful to find natural groupings in the dataset. For example, clusters may identify families which have similar structure, status and demographics.
      </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>2. Visualise within cluster variability</h2>
      <p>
        Dive down into the data, explore the dietary distribution of different clusters. Comparing distributions can highlight potential nutritional imbalances and help target interventions.
      </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>3. Look for seasonal trends in buying patterns</h2>
      <p>
        In addition to breaking down buying habbits over sub-populations, we can also visualise how the items bought by a group of families varies over time.
      </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

<!-- {% block scripts %}
 --><script src="{% static 'site/js/site.js' %}"></script>
<!-- {% endblock scripts %}
 -->